const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { x25519 } = require('@noble/curves/ed25519.js');
const agePqc = require('../lib/age_pqc');

// Hardware-free proof of the derived (label-based) X-Wing split-custody
// path's JS side - the browser twin of python-onlykey's
// tests/test_derived_xwing.py. No device, no FIDO2: "_deviceDerive()" below
// is a stand-in that generates a random X25519 key locally, exactly like the
// Python test's _device_derive(). Wiring this to the real device over
// FIDO2/CTAP2 (okcrypto_xwing_web_derive() on the firmware side) is later,
// separate work - see lib/age_pqc.js's module doc comment.
describe('Derived X-Wing split custody - JS math (age-pqc groundwork)', function () {
    function deviceDerive() {
        const skX = x25519.utils.randomSecretKey();
        const pkX = x25519.getPublicKey(skX);
        const mlkemSeed = crypto.randomBytes(32);
        return { skX, pkX, mlkemSeed };
    }

    it('recipient is 1216 bytes', function () {
        const { pkX, mlkemSeed } = deviceDerive();
        assert.strictEqual(agePqc.buildRecipient(pkX, mlkemSeed).length, 1216);
    });

    it('split decaps matches standard encaps', function () {
        const { skX, pkX, mlkemSeed } = deviceDerive();
        const recipient = agePqc.buildRecipient(pkX, mlkemSeed);

        const { sharedSecret: ssEnc, ciphertext: ct } = agePqc.xwingEncapsHost(recipient);
        assert.strictEqual(ct.length, 1120);

        const ssX = x25519.getSharedSecret(skX, agePqc.ctXOf(ct)); // device: X25519(sk_X, ct_X)
        const ssDec = agePqc.splitDecapsulate(ssX, ct, pkX, mlkemSeed); // host: ML-KEM half + combiner
        assert.deepStrictEqual(Buffer.from(ssDec), Buffer.from(ssEnc));
    });

    it('wrong device share fails ("no device => no decrypt")', function () {
        const { pkX, mlkemSeed } = deviceDerive();
        const recipient = agePqc.buildRecipient(pkX, mlkemSeed);
        const { sharedSecret: ssEnc, ciphertext: ct } = agePqc.xwingEncapsHost(recipient);
        const bad = agePqc.splitDecapsulate(new Uint8Array(32), ct, pkX, mlkemSeed); // no device ss_X
        assert.notDeepStrictEqual(Buffer.from(bad), Buffer.from(ssEnc));
    });

    it('deterministic recipient per seed', function () {
        const { pkX, mlkemSeed } = deviceDerive();
        assert.deepStrictEqual(
            Buffer.from(agePqc.buildRecipient(pkX, mlkemSeed)),
            Buffer.from(agePqc.buildRecipient(pkX, mlkemSeed))
        );
    });

    it('derived identity roundtrip', function () {
        for (const label of ['age:personal', 'alice@example.com', 'work']) {
            const ident = agePqc.encodeIdentity(label);
            assert.ok(ident.startsWith('AGE-PLUGIN-ONLYKEY-DERIVED-'));
            assert.deepStrictEqual(agePqc.decodeIdentity(ident), { derived: true, label });
        }
        // a slot-style identity is not a derived identity
        assert.strictEqual(agePqc.decodeIdentity('AGE-PLUGIN-ONLYKEY-1QQQ'), null);
    });

    // Beyond the 5 self-consistency checks above (mirroring
    // test_derived_xwing.py 1:1): this fixture was generated by
    // lib/py/gen_derived_xwing_vector.py running the actual Python reference
    // (derived_xwing.py + xwing.py) on fixed inputs, so this proves the JS
    // port isn't just internally consistent with itself - it's byte-for-byte
    // identical to what the CLI actually computes.
    it('matches python-onlykey derived_xwing.py byte-for-byte (fixed vector)', function () {
        const vectorPath = path.join(__dirname, 'fixtures', 'derived-xwing-vector.json');
        const v = JSON.parse(fs.readFileSync(vectorPath, 'utf8'));
        const b64 = (s) => Buffer.from(s, 'base64');

        const pkX = b64(v.pk_x);
        const mlkemSeed = b64(v.mlkem_seed);
        const ssX = b64(v.ss_x);
        const ciphertext = b64(v.ciphertext);

        const { publicKey: pkM } = agePqc.mlkemKeypairFromSeed(mlkemSeed);
        assert.deepStrictEqual(Buffer.from(pkM), b64(v.pk_m), 'pk_M mismatch vs python');

        const recipient = agePqc.buildRecipient(pkX, mlkemSeed);
        assert.deepStrictEqual(Buffer.from(recipient), b64(v.recipient), 'recipient mismatch vs python');

        assert.deepStrictEqual(Buffer.from(agePqc.ctXOf(ciphertext)), b64(v.ct_x), 'ct_X mismatch vs python');

        const ssDec = agePqc.splitDecapsulate(ssX, ciphertext, pkX, mlkemSeed);
        assert.deepStrictEqual(Buffer.from(ssDec), b64(v.shared_secret), 'shared secret mismatch vs python');
    });
});
